services:
  - type: web
    name: email-backend
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false